# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-11:
    name: build on Node v11 (like server)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x] # 10.x, 12.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install dependencies
      run: npm ci
    - run: npm run test:js
      env:
        NODE_ENV: test
        CONTENTFUL_HOOK_PW: ${{ secrets.CONTENTFUL_HOOK_PW }}
        CONTENTFUL_HOOK_USER: ${{ secrets.CONTENTFUL_HOOK_USER }}
        CONTENTFUL_TOKEN_PREVIEW: ${{ secrets.CONTENTFUL_TOKEN_PREVIEW }}
        CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
        CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
    - run: npm run test:css
    - run: npm run build:css
    - run: npm run build:js
    # - run: npm run test:integration
    #   env:
    #     SNAPSHOT_PATH: ${{ github.workspace }}
    #     NODE_ENV: test
    #     CONTENTFUL_HOOK_PW: ${{ secrets.CONTENTFUL_HOOK_PW }}
    #     CONTENTFUL_HOOK_USER: ${{ secrets.CONTENTFUL_HOOK_USER }}
    #     CONTENTFUL_TOKEN_PREVIEW: ${{ secrets.CONTENTFUL_TOKEN_PREVIEW }}
    #     CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
    #     CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
    # - uses: actions/upload-artifact@v2
    #   if: failure()
    #   with:
    #     name: Snapshots
    #     path: ${{ github.workspace }}/test_snaps
